### ISSUE TITLE
hi author?

### ISSUE THREAD

**Issue by marshellhu** [lucasxlu/TreeCNN#1]
hi，can you communicateme with qq? 975929354,It seems that there are some bugs in the programm?

**Comment by lucasxlu** [comment]
> hi，can you communicateme with qq? 975929354,It seems that there are some bugs in the programm?

Hi, THX for your attention, __there's no bug__. You may have to modify the model to fit your dataset. The current model is too big which needs lots of GPU resources to train and inference, we are going to perform model pruning and try some light-weighted backbone networks in the near future. Since this repo is used for my research paper, __I do not intent to update this code until my paper is accepted.__ 
:-)
